### PR TITLE
Fix window is not defined

### PR DESCRIPTION
**Pull request by titipakorn**
The problem has occurred when it has been rendered from the server side.

This code can avoid the problem and work perfectly.

### CODE REVIEW

**Comment by mirzapourh** [comment]
Hi,

Any ideas on when this would get merged?

Thanks

**Comment by oogali** [comment]
@titipakorn Why did you remove `build/` from the Git ignore patterns, and then include a number of files that were previously meant to be excluded?

**Comment by hack0001** [comment]
Having this problem on a server rendered application and was wondering if this fix will get merged?

**Comment by garetht** [comment]
@titipakorn thanks!

@hack0001 released as 0.11.1.

**Pull request merged**
