### PR TITLE
upgraded peer dependencies to react 16.2.0

### PR DESCRIPTION
**Pull request by aaronincincy**
This updates peer dependencies to react 16.2.0 and fixes the failing unit tests preset in #240.

### CODE REVIEW

**Comment by aaronincincy** [comment]
I'm not sure what's going on with the failed CI build.  I'll look at that when I get home this evening.

**Comment by aaronincincy** [comment]
@garetht  I tried to look into this, but I'm struggling to even know what the error is.  Can you provide any guidance on this?

**Comment by aaronincincy** [comment]
Ok, I did fix an issue on the examples pages and they're now behaving the same as the current version, however I'm still getting an issue with the CI build failing.  I'm not really sure where to go from here.

**Comment by mashehu** [comment]
I think I found the problem with the build fail. It was using a deprecated version of cypress, see #269. But the test seems now to be failing because of outdated dependencies...

**Comment by garetht** [comment]
Thanks for the help @aaronincincy and @mashehu! I'll make a release later today.

**Comment by NoelAramis** [comment]
Could you please update the @latest in the NPM repository, so that the npm install pulls the latest version from github? Thanks.

**Comment by jnarwold** [comment]
Any update on when we might get a release for this?

**Comment by schnubor** [comment]
+1 on the release? asking for a friend... ahem.

**Comment by garetht** [comment]
Sorry for the delay - will do this later today.

**Comment by garetht** [comment]
@NoelAramis @jnarwold @schnubor This has been released as 0.13.0

**Pull request merged**
