### PR TITLE
Adding disabled props

### PR DESCRIPTION
**Pull request by DefoyPhilip**
Adding a props called disabled that can be passed to the Infinite component.
While disabled, the overflowY is set to hidden making the list unscrollable.

Fix issue #122

### CODE REVIEW

**Comment by garetht** [comment]
Thanks @DefoyPhilip! There has been [another pull request](https://github.com/seatgeek/react-infinite/pull/130) addressing the same concern, and I'll have to think about which API is more desirable for a bit.

**Comment by DefoyPhilip** [comment]
ok! no problem :)

**Comment by garetht** [comment]
@DefoyPhilip The solution proposed in https://github.com/seatgeek/react-infinite/pull/130 can be used to override `overflowY`.

**Comment by DefoyPhilip** [comment]
ok! Thanks for the feedback!

**Pull request closed without merging**
