### PR TITLE
Update react in bower.json

### PR DESCRIPTION
**Pull request by jessicard**
I'm using React 0.12.2 and this component works. For now, I have just added it in manually.

### CODE REVIEW

**Comment by garetht** [comment]
Looks good, thanks!

**Comment by jessicard** [comment]
Thanks @garetht! Can you tag a new version so that I can use it? :)

**Comment by garetht** [comment]
Yup, done - was just fixing it for NPM as well.

**Comment by jessicard** [comment]
@garetht Wow, that was so fast. Thanks so much! :heart:

**Pull request merged**
